from pyspark.sql.types import *


class Schema:

    @staticmethod
    def booking_schema():
        booking_schema = StructType([StructField("act_date", TimestampType(), True),
                                     StructField("source", StringType(), True),
                                     StructField("pos_ctry", StringType(), True),
                                     StructField("pos_iata", StringType(), True),
                                     StructField("pos_oid", StringType(), True),
                                     StructField("rloc", StringType(), True),
                                     StructField("cre_date", StringType(), True),
                                     StructField("duration", StringType(), True),
                                     StructField("distance", StringType(), True),
                                     StructField("dep_port", StringType(), True),
                                     StructField("dep_city", StringType(), True),
                                     StructField("dep_ctry", StringType(), True),
                                     StructField("arr_port", StringType(), True),
                                     StructField("arr_city", StringType(), True),
                                     StructField("arr_ctry", StringType(), True),
                                     StructField("lst_port", StringType(), True),
                                     StructField("lst_city", StringType(), True),
                                     StructField("lst_ctry", StringType(), True),
                                     StructField("brd_port", StringType(), True),
                                     StructField("brd_city", StringType(), True),
                                     StructField("brd_ctry", StringType(), True),
                                     StructField("off_port", StringType(), True),
                                     StructField("off_city", StringType(), True),
                                     StructField("off_ctry", StringType(), True),
                                     StructField("mkt_port", StringType(), True),
                                     StructField("mkt_city", StringType(), True),
                                     StructField("mkt_ctry", StringType(), True),
                                     StructField("intl", StringType(), True),
                                     StructField("route", StringType(), True),
                                     StructField("carrier", StringType(), True),
                                     StructField("bkg_class", StringType(), True),
                                     StructField("cab_class", StringType(), True),
                                     StructField("brd_time", StringType(), True),
                                     StructField("off_time", StringType(), True),
                                     StructField("pax", IntegerType(), True),
                                     StructField("year", IntegerType(), True),
                                     StructField("month", IntegerType(), True),
                                     StructField("oid", StringType(), True),
                                     StructField("_corrupt_record", StringType(), True)])
        return booking_schema

    @staticmethod
    def search_schema():
        search_schema = StructType([
            StructField("Date", StringType(), True),
            StructField("Time", TimestampType(), True),
            StructField("TxnCode", StringType(), True),
            StructField("OfficeID", StringType(), True),
            StructField("Country", StringType(), True),
            StructField("Origin", StringType(), True),
            StructField("Destination", StringType(), True),
            StructField("RoundTrip", IntegerType(), True),
            StructField("NbSegments", IntegerType(), True),
            StructField("Seg1Departure", StringType(), True),
            StructField("Seg1Arrival", StringType(), True),
            StructField("Seg1Date", TimestampType(), True),
            StructField("Seg1Carrier", StringType(), True),
            StructField("Seg1BookingCode", StringType(), True),
            StructField("Seg2Departure", StringType(), True),
            StructField("Seg2Arrival", StringType(), True),
            StructField("Seg2Date", TimestampType(), True),
            StructField("Seg2Carrier", StringType(), True),
            StructField("Seg2BookingCode", StringType(), True),
            StructField("Seg3Departure", StringType(), True),
            StructField("Seg3Arrival", StringType(), True),
            StructField("Seg3Date", TimestampType(), True),
            StructField("Seg3Carrier", StringType(), True),
            StructField("Seg3BookingCode", StringType(), True),
            StructField("Seg4Departure", StringType(), True),
            StructField("Seg4Arrival", StringType(), True),
            StructField("Seg4Date", TimestampType(), True),
            StructField("Seg4Carrier", StringType(), True),
            StructField("Seg4BookingCode", StringType(), True),
            StructField("Seg5Departure", StringType(), True),
            StructField("Seg5Arrival", StringType(), True),
            StructField("Seg5Date", TimestampType(), True),
            StructField("Seg5Carrier", StringType(), True),
            StructField("Seg5BookingCode", StringType(), True),
            StructField("Seg6Departure", StringType(), True),
            StructField("Seg6Arrival", IntegerType(), True),
            StructField("Seg6Date", StringType(), True),
            StructField("Seg6Carrier", StringType(), True),
            StructField("Seg6BookingCode", IntegerType(), True),
            StructField("From", StringType(), True),
            StructField("IsPublishedForNeg", StringType(), True),
            StructField("IsFromInternet", StringType(), True),
            StructField("IsFromVista", StringType(), True),
            StructField("TerminalID", StringType(), True),
            StructField("InternetOffice", StringType(), True),
            StructField("_corrupt_record", StringType(), True)
        ])
        return search_schema